Use correct colors for info card, add icon, remove unused icon.
HedvigInsurance/android pull request #1626
Opened 2023-05-30 14:12 UTC by hugokallstrom

Fix path for downloaded file.
Set action bar type for scaffold.
Fix designs.

2023-05-30 18:01 UTC, StylianosGakis requested changes
I think some important notes around theming, especially for the changed colors in the dark color scheme which I think we'd need to not merge in. And continuing from that, some of the usages of those colors I am curious about.

2023-05-31 07:11 UTC, hugokallstrom commented on app/app/src/main/kotlin/com/hedvig/app/feature/home/ui/HomeFragment.kt
> -            Spacer(Modifier.height(8.dp))
Makes sense, good catch

2023-05-31 07:14 UTC, hugokallstrom commented on app/core/design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/textfield/HedvigTextFieldDefaults.kt
> -        .borderLine(enabled, isError, interactionSource, colors, shape),
Yeah after syncing with William we decided to remove this. Its not present on web either so maybe its not used at all.

2023-05-31 07:18 UTC, hugokallstrom commented on app/core/design-system/src/main/kotlin/com/hedvig/android/core/designsystem/material3/HedvigMaterial3ColorScheme.kt
> +  onInfoContainer = blue_900, // blue_900,
Oh my bad, was meaning to change light mode only.

2023-05-31 07:28 UTC, hugokallstrom commented on app/core/ui/src/main/kotlin/com/hedvig/android/core/ui/infocard/InfoCard.kt
> +        color = MaterialTheme.colorScheme.onInfoElement,
Ah that works great, thanks. VectorInfoCard just means we can pass a ImageVector icon. We have a DrawableInfoCard as well :)

2023-05-31 07:40 UTC, hugokallstrom commented on app/feature/travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/GenerateTravelCertificateInput.kt
> +              .height(32.dp),
Good catch!

2023-05-31 11:27 UTC, StylianosGakis commented on app/core/design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/textfield/HedvigTextFieldDefaults.kt
> -        .borderLine(enabled, isError, interactionSource, colors, shape),
Aha makes sense. Then we can also remove this https://github.com/HedvigInsurance/android/blob/cd2ac58c9925bbaaf837caa2ae01b88eda8c544d/app/core/design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/textfield/HedvigTextField.kt#L837 and this https://github.com/HedvigInsurance/android/blob/f068ed72af498799bcb245dcedeb923fbd86b4d2/app/core/design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/textfield/HedvigTextFieldDefaults.kt#L104-L147 and if there's anything else that would be unused after this change.

2023-05-31 11:28 UTC, StylianosGakis commented on app/core/ui/src/main/kotlin/com/hedvig/android/core/ui/infocard/InfoCard.kt
> +        color = MaterialTheme.colorScheme.onInfoElement,
Aha of course! I really didn't put 1 and 1 together back then to understand what Vector means there 😅 Thanks for explaining!

2023-05-31 11:29 UTC, StylianosGakis approved these changes
Nice! Thanks for addressing all the comments 🙏

2023-05-31 11:57 UTC, merged