Feature/hvg 185 inusrance tab base
HedvigInsurance/android pull request #344
Opened 2020-10-20 14:43 UTC by MathiasOhrstrom

Item from design: []

### Screenshots

Screenshot 1
Screenshot 2
...

### Checklist

- [ ] Functionality is covered by an integration test
- [x] Functionality is accessible in engineering mode

2020-10-21 08:03 UTC, hedvigoscar requested changes

2020-10-21 08:03 UTC, hedvigoscar commented on testdata/src/main/java/com/hedvig/app/testdata/dashboard/Data.kt
> +    activeInFutureAndTerminatedInFutureStatus = ContractStatusFragment.AsActiveInFutureAndTerminatedInFutureStatus(
We can use the same pattern as we've used in the `HomeDataBuilder` here wrt. contract status - i.e use an enum to switch between the cases.

2020-10-21 08:03 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt
> +                        //TODO open info activity
The detail activity exists, we can launch it from here 🙂

2020-10-21 08:04 UTC, hedvigoscar commented
Also, we're a bit low on integration tests for this functionality, I think we should remedy that 😉

2020-10-21 08:35 UTC, MathiasOhrstrom commented on app/src/main/java/com/hedvig/app/util/extensions/ModelExtensions.kt
> +//TODO fix real translation
No idea, will have to ask Zak for that

2020-10-21 08:38 UTC, MathiasOhrstrom commented on app/src/main/res/drawable/card_background.xml
> +            <gradient android:startColor="#fbd7ec" android:endColor="#e4def7" android:angle="0" android:type="linear"/>
Two, this one for gradient and the default one which is just gray

2020-10-21 08:45 UTC, hedvigoscar commented on app/src/main/res/drawable/card_background.xml
> +            <gradient android:startColor="#fbd7ec" android:endColor="#e4def7" android:angle="0" android:type="linear"/>
I think there was a separate one for Travel contracts, right? 😉

2020-10-21 08:46 UTC, MathiasOhrstrom commented on app/src/main/res/layout/insurance_contract_card.xml
> +            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
You mean to make the list wrap instead of scroll?

2020-10-21 08:51 UTC, MathiasOhrstrom commented on app/src/main/res/drawable/card_background.xml
> +            <gradient android:startColor="#fbd7ec" android:endColor="#e4def7" android:angle="0" android:type="linear"/>
Okey. I thought when we said to only use static gradient to only use one for all contracts. But ill add the one for travel as well

2020-10-21 08:52 UTC, hedvigoscar commented on app/src/main/res/layout/insurance_contract_card.xml
> +            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
Yes! I think that is probably the desired behaviour.

2020-10-22 07:57 UTC, hedvigoscar approved these changes
Approved upon fixing comments!

2020-10-22 07:57 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/insurance/ui/ContractPillAdapter.kt
> +                            text.text = "${
This should be a templated string in Lokalise, that we use in this way:

```kotlin
text.text.setText(R.string,.insurance_tab_covers_you_tag, item.noOfCoInsured)
```

2020-10-22 07:57 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt
> +                        contractStatus.asActiveStatus?.let {
For correctness, we should probably apply the gray background to the card when it is in an inactive state.

2020-10-22 07:57 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt
> +                        )
```suggestion
                        root.context.startActivity(
                            ContractDetailActivity.newInstance(root.context),
                        )
```

2020-10-22 07:57 UTC, hedvigoscar commented on app/src/main/res/layout/insurance_contract_card.xml
> +            android:layout_width="@dimen/base_margin_triple"
I think we should introduce a separate `dimen` for this, else we're going to have weird behaviours if we decide to switch around `base_margin`s 😬

2020-10-22 12:13 UTC, merged