HVG-385: Refactor `PaymentActivity`
HedvigInsurance/android pull request #389
Opened 2020-11-20 10:18 UTC by hedvigoscar

### Checklist

- [X] Functionality is covered by an integration test
- [X] Functionality is accessible in engineering mode

2020-11-20 14:46 UTC, MathiasOhrstrom requested changes
Now i understand why this screen was so complicated 😅

2020-11-23 08:28 UTC, hedvigoscar commented on app/src/androidTest/java/com/hedvig/app/feature/payment/FailedPaymentsTest.kt
> +                        )
Valid - the standard for code quality is different in the test modules - see this excellent blog post on the subject https://testing.googleblog.com/2019/12/testing-on-toilet-tests-too-dry-make.html

2020-11-23 08:30 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt
> +            }
It can, but it does not need to - it's a static initialization that does not depend at all on the data. Hence, it does not need to be repeated 🙂

2020-11-23 08:31 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt
> +        }
Perhaps, I think the penalty from trying to generify it will be larger than the gains from doing so though 🧐

2020-11-23 08:38 UTC, MathiasOhrstrom commented on app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt
> +        }
What could the penalty be? We always use this after a check to see if the data is not the correct type

2020-11-23 08:43 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt
> +        }
Actually, we could probably generify it decently with an extension method. Hold on a minute!

2020-11-23 09:43 UTC, MathiasOhrstrom approved these changes

2020-11-23 14:20 UTC, merged