more options
HedvigInsurance/android pull request #397
Opened 2020-11-25 16:05 UTC by MathiasOhrstrom

Item from design: []

### Checklist

- [x] Functionality is covered by an integration test
- [x] Functionality is accessible in engineering mode

2020-11-26 10:52 UTC, hedvigoscar requested changes

2020-11-26 10:52 UTC, hedvigoscar commented on app/src/main/res/layout/user_id.xml
> +<?xml version="1.0" encoding="utf-8"?>
`user_id.xml`, `user_id_error.xml` and `version.xml` appear to be more or less identical - should we re-use the layout?

2020-11-26 10:52 UTC, hedvigoscar commented on app/src/main/res/menu/embark_menu.xml
> +        app:showAsAction="ifRoom" />
This can probably be `always`, right?
```suggestion
        app:showAsAction="always" />
```

2020-11-26 10:52 UTC, hedvigoscar commented on app/src/main/res/layout/user_id.xml
> +        android:layout_height="wrap_content"
These `TextView`s might need to have `match_constraint` (`0dp`) as width, in order to wrap correctly 🙂

2020-11-26 10:52 UTC, hedvigoscar commented on app/src/main/res/layout/user_id_error.xml
> +    android:layout_height="@dimen/more_options_list_item_height">
Can we have this height be reflected by its contents and use `wrap_content`? It's usually safer, in cases where the content needs to be larger than a fixed height.

2020-11-27 10:54 UTC, MathiasOhrstrom commented on app/src/main/java/com/hedvig/app/feature/embark/ui/MoreOptionsActivity.kt
> +                if (result.isSuccess) {
I get how this helps with code readability, but how does it reduce indentation?

2020-11-27 10:57 UTC, MathiasOhrstrom commented on app/src/main/java/com/hedvig/app/feature/embark/ui/MoreOptionsAdapter.kt
> +            }
I guess this is just to make the code prettier?

2020-11-27 11:18 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/embark/ui/MoreOptionsActivity.kt
> +                if (result.isSuccess) {
Given that you don't need to write the `else`-clause if you've already returned early, you reduce the level of indentation by one 🙂

2020-11-30 15:24 UTC, merged