HVG-485 toolbar
HedvigInsurance/android pull request #423
Opened 2020-12-22 12:33 UTC by MathiasOhrstrom

2021-01-08 15:00 UTC, hedvigoscar requested changes

2021-01-08 15:00 UTC, hedvigoscar commented on app/src/main/res/menu/embark_tooltip_menu.xml
> +        android:title="TODO Tooltip"
👮

2021-01-11 12:19 UTC, MathiasOhrstrom commented on app/src/main/res/layout/tooltip_bottom_sheet.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
I think this is a reasonable use for `ConstraintLayout` since we want to have the X to the left and the pill in the middle

2021-01-11 12:25 UTC, MathiasOhrstrom commented on app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt
> +    override fun onCreateOptionsMenu(menu: Menu): Boolean {
Do you mean `app:menu=""` in xml? If so shouldn’t we have it this way since we need to alternate between two different menus?

2021-01-11 13:58 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt
> +    override fun onCreateOptionsMenu(menu: Menu): Boolean {
I think we can probably use `toolbar.menu.clear` and `toolbar.inflateMenu(R.menu.some_menu)`, perhaps?

2021-01-11 13:59 UTC, hedvigoscar commented on app/src/main/res/layout/tooltip_bottom_sheet.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
Right you are. My bad 😬

2021-01-11 14:31 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt
> +    override fun onCreateOptionsMenu(menu: Menu): Boolean {
We can probably use a combination of `toolbar.menu.clear()` and `toolbar.inflateMenu()`

2021-01-12 14:48 UTC, merged