APP-37: Simple Sign Auth-Screen
HedvigInsurance/android pull request #497
Opened 2021-03-23 12:59 UTC by hedvigoscar

Deferred for now:

- Keyboard animation. I love it, but it's too hard to get done right now
- Split the thing out to a module. Given that we did not merge the instant app
  code, I'm left with too little inspiration to get this done in time

### Checklist

- [X] Functionality is covered by an integration test
- [X] Functionality is accessible in engineering mode

2021-03-25 08:06 UTC, hugokallstrom requested changes

2021-03-25 08:06 UTC, hugokallstrom commented on app/src/main/java/com/hedvig/app/feature/zignsec/ui/IdentityInputFragment.kt
> +                }
I think we could be very defensive here and show a generic error, or maybe a kind of market unavailable-error. I understand this "shouldn't" happen, but I also think its scary to leave this as a no-op.

2021-03-25 08:16 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/zignsec/SimpleSignAuthenticationViewModel.kt
> +
It's used in `ZignSecWebViewFragment` 🙂

2021-03-25 08:19 UTC, hedvigoscar commented on app/src/main/java/com/hedvig/app/feature/zignsec/SimpleSignAuthenticationViewModel.kt
> +            Market.NO -> {
I'm not sure that I'm understanding you entirely here, perhaps you can explain it later in a call 😬

2021-03-26 08:38 UTC, hedvigoscar commented
I'm going to merge this for now as we want to be able to test this, but let's look at the last remaining issue when you're back.

2021-03-26 08:38 UTC, merged