APP-1661: Generic auth login
HedvigInsurance/android pull request #996
Opened 2022-05-11 11:58 UTC by hugokallstrom

Add button in QR code dialog which opens generic auth flow. This will only work for Qasa members, but we should be able to activate it for all members without doing any changes in the clients.

2022-05-11 11:59 UTC, oscarnylander requested changes

2022-05-11 11:59 UTC, oscarnylander commented on app/src/main/res/layout/dialog_authenticate.xml
> +        android:text="Login with email" />
Needs string resource

2022-05-11 11:59 UTC, hugokallstrom commented on app/src/main/res/layout/dialog_authenticate.xml
> +        android:text="Login with email" />
🙈

2022-05-12 08:19 UTC, hugokallstrom commented on app/src/main/res/layout/dialog_authenticate.xml
> +        android:text="Login with email" />
Fixed 👍

2022-05-12 11:00 UTC, merged